version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nest_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  # backend:
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: nest_backend
  #   environment:
  #     - POSTGRES_HOST=postgres # Importante: aquí el host es el nombre del servicio
  #     - POSTGRES_PORT=${POSTGRES_PORT}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   # command: npm run start:dev # Descomenta para desarrollo

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: vue_frontend
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: